name: bibleapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+30

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  #flutter_easyloading: ^1.1.3
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_staggered_grid_view: "^0.2.7"
  # 屏幕适配方案
  flutter_screenutil: ^1.0.2
  # Dart Http请求库
  dio: ^3.0.9
  http: ^0.12.0+4
  #toast提示
  toast: ^0.1.4
  #Gridview slect class 动画
  flutter_staggered_animations: ^0.1.2
  #持久化存储
  shared_preferences: ^0.5.6+3
  # slect subject 动画从下面进入
  animate_do: ^1.6.3
  #记录时间
  time: "^1.2.0"
  sqflite:
  path:
  path_provider:
  html_unescape: ^1.0.1+3
  flutter_widgets: ^0.1.12
  flutter_webview_plugin: ^0.3.10+2
  flutter_tts: ^1.2.6
  synchronized: ^2.2.0
  share: ^0.6.3+6
  modal_progress_hud: ^0.1.3
  flutter_i18n: ^0.13.0
  popup_menu: ^1.0.5
  font_awesome_flutter: ^8.8.1
  rflutter_alert: ^1.0.3
  percent_indicator: ^2.1.3
  speech_to_text: ^2.2.0
  wakelock: ^0.1.4+1
  table_calendar: ^2.2.3
  intl: ^0.16.0
  flutter_native_admob: ^2.1.0
  firebase_admob: ^0.9.3+2
  back_button_interceptor: ^4.2.4
  flutter_launcher_icons: ^0.7.5
  flutter_native_splash: ^0.1.9
  catcher: ^0.3.14
  translator: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter_icons:
  image_path_android: "assets/images/CrownBibleIconAnd.png"
  image_path_ios: "assets/images/CrownBibleIconIOS.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_native_splash:
  image: assets/images/CrownBibleIcon.png
  color: "42a5f5"

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/json/bible_cuv.json
    - assets/json/bible_title_cuv.json
    - assets/i18n/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
